"""Stable sidecar API surface."""

from .http_server import SidecarHTTPServer, build_argument_parser, create_http_server, main, serve_http
from .service import (
    create_knowledge_base,
    get_config_snapshot,
    get_health,
    get_hermes_bridge_health,
    get_hermes_capability_snapshot,
    get_hermes_memory_snapshot,
    get_hermes_sessions_snapshot,
    get_hermes_skills_snapshot,
    get_hermes_tools_snapshot,
    get_meta_harness_benchmark_smoke,
    get_meta_harness_dependency_snapshot,
    ingest_file_document,
    ingest_text_document,
    ingest_url_document,
    invoke_chat_completion,
    invoke_formal_analysis,
    list_knowledge_bases,
    list_models,
    list_providers,
    list_rules,
    list_skills,
    run_agent_loop,
    stream_agent_loop,
    stream_chat_completion,
    search_knowledge_base,
)

__all__ = [
    "SidecarHTTPServer",
    "build_argument_parser",
    "create_knowledge_base",
    "create_http_server",
    "get_config_snapshot",
    "get_health",
    "get_hermes_bridge_health",
    "get_hermes_capability_snapshot",
    "get_hermes_memory_snapshot",
    "get_hermes_sessions_snapshot",
    "get_hermes_skills_snapshot",
    "get_hermes_tools_snapshot",
    "get_meta_harness_benchmark_smoke",
    "get_meta_harness_dependency_snapshot",
    "ingest_file_document",
    "ingest_text_document",
    "ingest_url_document",
    "invoke_chat_completion",
    "invoke_formal_analysis",
    "list_knowledge_bases",
    "list_models",
    "list_providers",
    "list_rules",
    "list_skills",
    "main",
    "run_agent_loop",
    "stream_agent_loop",
    "search_knowledge_base",
    "serve_http",
    "stream_chat_completion",
]
