"""Minimum sidecar service API — thin re-export layer.

All implementation has moved to ``pyc_hermes_agent.sidecar_api.services.*``.
This module re-exports every public name so that existing imports from
``pyc_hermes_agent.sidecar_api.service`` continue to work unchanged.
"""

from pyc_hermes_agent.sidecar_api.services import (  # noqa: F401
    SIDECAR_API_VERSION,
    MRAGServiceRegistry,
    create_knowledge_base,
    create_skill_patch_draft,
    delete_skill_patch_draft,
    export_office_artifact_bundle,
    get_a2a_capability_surface,
    get_config_snapshot,
    get_health,
    get_hermes_bridge_health,
    get_hermes_capability_snapshot,
    get_hermes_memory_snapshot,
    get_hermes_sessions_snapshot,
    get_hermes_skills_snapshot,
    get_hermes_tools_snapshot,
    get_meta_harness_benchmark_smoke,
    get_meta_harness_dependency_snapshot,
    get_meta_harness_value_proof_benchmark,
    get_runtime_paths_snapshot,
    ingest_file_document,
    ingest_pdf_document,
    ingest_text_document,
    ingest_url_document,
    materialize_text_document,
    invoke_chat_completion,
    invoke_formal_analysis,
    list_asset_inventory,
    list_knowledge_bases,
    list_models,
    list_providers,
    list_rules,
    list_sidecar_artifacts,
    list_skill_patch_drafts,
    list_skills,
    make_error_response,
    rebuild_mrag_chunk_index,
    run_agent_loop,
    search_knowledge_base,
    stream_agent_loop,
    stream_chat_completion,
    suggest_skill_patch_draft_from_session,
)

__all__ = [
    "SIDECAR_API_VERSION",
    "MRAGServiceRegistry",
    "create_knowledge_base",
    "create_skill_patch_draft",
    "delete_skill_patch_draft",
    "export_office_artifact_bundle",
    "get_a2a_capability_surface",
    "get_config_snapshot",
    "get_health",
    "get_hermes_bridge_health",
    "get_hermes_capability_snapshot",
    "get_hermes_memory_snapshot",
    "get_hermes_sessions_snapshot",
    "get_hermes_skills_snapshot",
    "get_hermes_tools_snapshot",
    "get_meta_harness_benchmark_smoke",
    "get_meta_harness_dependency_snapshot",
    "get_meta_harness_value_proof_benchmark",
    "get_runtime_paths_snapshot",
    "ingest_file_document",
    "ingest_pdf_document",
    "ingest_text_document",
    "ingest_url_document",
    "materialize_text_document",
    "invoke_chat_completion",
    "invoke_formal_analysis",
    "list_asset_inventory",
    "list_knowledge_bases",
    "list_models",
    "list_providers",
    "list_rules",
    "list_sidecar_artifacts",
    "list_skill_patch_drafts",
    "list_skills",
    "make_error_response",
    "rebuild_mrag_chunk_index",
    "run_agent_loop",
    "search_knowledge_base",
    "stream_agent_loop",
    "stream_chat_completion",
    "suggest_skill_patch_draft_from_session",
]
