"""Service sub-package — re-exports all service functions."""

from pyc_hermes_agent.sidecar_api.services.common import (
    SIDECAR_API_VERSION,
    get_config_snapshot,
    get_health,
    get_runtime_paths_snapshot,
    list_asset_inventory,
    list_models,
    list_providers,
    list_rules,
    list_sidecar_artifacts,
    make_error_response,
)
from pyc_hermes_agent.sidecar_api.services.chat_service import (
    invoke_chat_completion,
    run_agent_loop,
    stream_agent_loop,
    stream_chat_completion,
)
from pyc_hermes_agent.sidecar_api.services.meta_service import (
    get_meta_harness_benchmark_smoke,
    get_meta_harness_dependency_snapshot,
    get_meta_harness_value_proof_benchmark,
    invoke_formal_analysis,
)
from pyc_hermes_agent.sidecar_api.services.mrag_service import (
    MRAGServiceRegistry,
    create_knowledge_base,
    ingest_file_document,
    ingest_pdf_document,
    ingest_text_document,
    ingest_url_document,
    list_knowledge_bases,
    rebuild_mrag_chunk_index,
    search_knowledge_base,
)
from pyc_hermes_agent.sidecar_api.services.skill_service import (
    get_hermes_bridge_health,
    get_hermes_capability_snapshot,
    get_hermes_memory_snapshot,
    get_hermes_sessions_snapshot,
    get_hermes_skills_snapshot,
    get_hermes_tools_snapshot,
    list_skills,
)
from pyc_hermes_agent.sidecar_api.services.office_artifacts import export_office_artifact_bundle

__all__ = [
    "SIDECAR_API_VERSION",
    "MRAGServiceRegistry",
    "create_knowledge_base",
    "get_config_snapshot",
    "get_health",
    "get_hermes_bridge_health",
    "get_hermes_capability_snapshot",
    "get_hermes_memory_snapshot",
    "get_hermes_sessions_snapshot",
    "get_hermes_skills_snapshot",
    "get_hermes_tools_snapshot",
    "get_meta_harness_benchmark_smoke",
    "get_meta_harness_dependency_snapshot",
    "get_meta_harness_value_proof_benchmark",
    "get_runtime_paths_snapshot",
    "ingest_file_document",
    "ingest_pdf_document",
    "ingest_text_document",
    "ingest_url_document",
    "invoke_chat_completion",
    "invoke_formal_analysis",
    "list_asset_inventory",
    "list_knowledge_bases",
    "list_models",
    "list_providers",
    "list_rules",
    "list_sidecar_artifacts",
    "list_skills",
    "export_office_artifact_bundle",
    "make_error_response",
    "rebuild_mrag_chunk_index",
    "run_agent_loop",
    "search_knowledge_base",
    "stream_agent_loop",
    "stream_chat_completion",
]
