"""Static capability registry for MetaFramework v0.1."""

from __future__ import annotations

from typing import Dict, List, Optional

from metaframework.core.evidence import EvidenceLevel
from metaframework.core.types import CapabilitySpec


CAPABILITY_REGISTRY: Dict[str, CapabilitySpec] = {
    "stats.rigor.bootstrap_fdr": CapabilitySpec(
        capability_id="stats.rigor.bootstrap_fdr",
        display_name="Bootstrap + FDR Rigor",
        category="statistics",
        engine_module="metaframework.engines.statistics.rigor",
        engine_class="RigorEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_fields=["series", "change_indices"],
        tags=["bootstrap", "fdr", "time-series"],
        description="Moving block bootstrap and BH-FDR rigor checks for time-series candidates.",
    ),
    "causal.effect.scm": CapabilitySpec(
        capability_id="causal.effect.scm",
        display_name="Structural Causal Model",
        category="causal",
        engine_module="metaframework.engines.causal.scm",
        engine_class="SCMEngine",
        default_evidence=EvidenceLevel.C2,
        max_evidence=EvidenceLevel.C3_PLUS,
        required_dependencies=["numpy"],
        required_fields=["df", "cause", "effect"],
        tags=["causal", "scm", "iv", "backdoor"],
        legacy_aliases=["A-12-SCM"],
        description="Backdoor or IV-style causal estimation with evidence clamping.",
    ),
    "causal.effect.synthetic_control": CapabilitySpec(
        capability_id="causal.effect.synthetic_control",
        display_name="Synthetic Control",
        category="causal",
        engine_module="metaframework.engines.causal.synthetic_control",
        engine_class="SyntheticControlEngine",
        default_evidence=EvidenceLevel.C2,
        max_evidence=EvidenceLevel.C3,
        required_dependencies=["numpy"],
        required_fields=["y_treat", "y_donors", "intervention_idx"],
        tags=["causal", "panel", "synthetic-control"],
        legacy_aliases=["A-12-SYNTH"],
        description="Weighted donor-based counterfactual estimation for comparative case studies.",
    ),
    "causal.effect.did": CapabilitySpec(
        capability_id="causal.effect.did",
        display_name="Difference in Differences",
        category="causal",
        engine_module="metaframework.engines.causal.did",
        engine_class="DiDEngine",
        default_evidence=EvidenceLevel.C2,
        max_evidence=EvidenceLevel.C3,
        required_dependencies=["numpy"],
        required_fields=["treat_pre", "treat_post", "control_pre", "control_post"],
        tags=["causal", "did"],
        description="2x2 DiD estimation with evidence clamping and explicit assumption warning.",
    ),
    "complex.early_warning.csd": CapabilitySpec(
        capability_id="complex.early_warning.csd",
        display_name="Critical Slowing Down",
        category="complex",
        engine_module="metaframework.engines.complex.csd",
        engine_class="CSDEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy", "scipy"],
        required_fields=["series"],
        tags=["csd", "complex-systems", "early-warning"],
        legacy_aliases=["A-16"],
        description="Phenomenological early-warning detection via AR1 and variance trends.",
    ),
    "complex.transition.hysteresis": CapabilitySpec(
        capability_id="complex.transition.hysteresis",
        display_name="Hysteresis Detection",
        category="complex",
        engine_module="metaframework.engines.complex.hysteresis",
        engine_class="HysteresisEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C2,
        required_dependencies=["numpy"],
        required_fields=["x_forward", "y_forward", "x_reverse", "y_reverse"],
        tags=["complex", "hysteresis", "path-dependence"],
        description="Detection of path dependence and multi-stability from forward and reverse sweeps.",
    ),
    "network.centrality.pagerank": CapabilitySpec(
        capability_id="network.centrality.pagerank",
        display_name="PageRank",
        category="network",
        engine_module="metaframework.engines.network.pagerank",
        engine_class="PageRankEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["adjacency_matrix"],
        tags=["network", "pagerank", "centrality"],
        legacy_aliases=["A-22", "A-22-NETWORK"],
        description="Graph centrality ranking via power iteration on adjacency-derived transition matrix.",
    ),
    "network.robustness.percolation": CapabilitySpec(
        capability_id="network.robustness.percolation",
        display_name="Network Percolation",
        category="network",
        engine_module="metaframework.engines.network.percolation",
        engine_class="PercolationEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["adjacency_matrix"],
        tags=["network", "percolation", "robustness"],
        description="Connectivity robustness analysis under node removal.",
    ),
    "network.failure.cascade": CapabilitySpec(
        capability_id="network.failure.cascade",
        display_name="Cascading Failure",
        category="network",
        engine_module="metaframework.engines.network.cascade",
        engine_class="CascadingFailureEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["adjacency_matrix"],
        tags=["network", "cascade", "failure"],
        description="Load redistribution cascade simulation after an initial attack.",
    ),
    "network.diffusion.sir": CapabilitySpec(
        capability_id="network.diffusion.sir",
        display_name="Network SIR",
        category="network",
        engine_module="metaframework.engines.network.sir",
        engine_class="SIREngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["adjacency_matrix"],
        tags=["network", "sir", "diffusion"],
        description="Network diffusion simulation for SIR-style contagion dynamics.",
    ),
    "extended.state.kalman_goal": CapabilitySpec(
        capability_id="extended.state.kalman_goal",
        display_name="Kalman Goal Tracking",
        category="extended",
        engine_module="metaframework.engines.extended.kalman",
        engine_class="KalmanGoalEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["progress_series"],
        tags=["extended", "kalman", "state-space"],
        maturity="extended",
        legacy_aliases=["A-14-PERS-GOAL-LIMIT"],
        description="Dynamic state tracking for progress trajectories using a simple Kalman update.",
    ),
    "extended.state.habit_hmm": CapabilitySpec(
        capability_id="extended.state.habit_hmm",
        display_name="Habit HMM Stage Detection",
        category="extended",
        engine_module="metaframework.engines.extended.hmm",
        engine_class="HabitHMMEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy", "scipy"],
        required_fields=["compliance"],
        tags=["extended", "hmm", "state-detection"],
        maturity="extended",
        legacy_aliases=["A-14-PERS-HABIT-LIMIT"],
        description="Three-state habit stage detection using a simplified HMM-like EM routine.",
    ),
    "extended.survival.cox": CapabilitySpec(
        capability_id="extended.survival.cox",
        display_name="Cox-style Survival Analysis",
        category="extended",
        engine_module="metaframework.engines.extended.cox",
        engine_class="CoxSurvivalEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["df"],
        tags=["extended", "cox", "survival"],
        maturity="extended",
        legacy_aliases=["A-13-ORG-CHURN-LIMIT"],
        description="Predictive survival-style ranking with hazard-ratio-like outputs.",
    ),
    "extended.efficiency.dea": CapabilitySpec(
        capability_id="extended.efficiency.dea",
        display_name="DEA Efficiency Frontier",
        category="extended",
        engine_module="metaframework.engines.extended.dea",
        engine_class="DEAEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy", "scipy"],
        required_fields=["teams"],
        tags=["extended", "dea", "efficiency"],
        maturity="extended",
        legacy_aliases=["A-15-TEAM-PROD-LIMIT"],
        description="Relative efficiency frontier estimation using a CCR-style DEA formulation.",
    ),
    "extended.queueing.mmc": CapabilitySpec(
        capability_id="extended.queueing.mmc",
        display_name="M/M/c Queueing",
        category="extended",
        engine_module="metaframework.engines.extended.queueing",
        engine_class="QueueingEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=[],
        required_fields=["task_arrival_rate", "task_completion_rate"],
        tags=["extended", "queueing", "mmc"],
        maturity="extended",
        legacy_aliases=["A-15-TEAM-SIZE-LIMIT"],
        description="Queueing tradeoff estimation for staffing and waiting-time optimization.",
    ),
    "extended.project.evm": CapabilitySpec(
        capability_id="extended.project.evm",
        display_name="Project EVM",
        category="extended",
        engine_module="metaframework.engines.extended.evm",
        engine_class="EVMEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["planned_value", "earned_value", "actual_cost"],
        tags=["extended", "evm", "project-management"],
        maturity="extended",
        description="Earned value management metrics and completion forecasting.",
    ),
    "extended.learning.curve": CapabilitySpec(
        capability_id="extended.learning.curve",
        display_name="Learning Curve",
        category="extended",
        engine_module="metaframework.engines.extended.learning",
        engine_class="LearningCurveEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy"],
        required_fields=["trials", "performance"],
        tags=["extended", "learning", "power-law"],
        maturity="extended",
        description="Wright-style power law learning curve estimation and forecasting.",
    ),
    "extended.team.conflict_signal": CapabilitySpec(
        capability_id="extended.team.conflict_signal",
        display_name="Conflict Signal Detection",
        category="extended",
        engine_module="metaframework.engines.extended.conflict",
        engine_class="ConflictSignalEngine",
        default_evidence=EvidenceLevel.C1,
        max_evidence=EvidenceLevel.C1,
        required_dependencies=["numpy", "pandas", "scipy"],
        required_fields=[],
        tags=["extended", "team", "conflict"],
        maturity="extended",
        description="Interaction anomaly detection for early conflict warning signals.",
    ),
}


def get_capability(capability_id: str) -> Optional[CapabilitySpec]:
    return CAPABILITY_REGISTRY.get(capability_id)


def list_capabilities() -> List[CapabilitySpec]:
    return list(CAPABILITY_REGISTRY.values())
